### PR TITLE
Added automatic return back to Jekyll site

### PR DESCRIPTION
**Pull request by IQAndreas**
Plus a slight error message in the rare case that the comment email is unable to send.

### CODE REVIEW

**Comment by IQAndreas** [comment]
Added fix for comments given by users who haven't filled in the `website` field.

**Comment by mpalmer** [comment]
The "problem sending the comment" change should be a separate commit, and the pull request shouldn't include your fix for issue #2.  If you'd like to fix those up, I'll merge your changes -- they look OK on the whole.

**Comment by IQAndreas** [comment]
> The "problem sending the comment" change should be a separate commit

Good point, I'll separate those two off into separate commits.

> The pull request shouldn't include your fix for issue #2

I tried sending them as separate pull requests, but GitHub gave a notice along the lines of _"You already have an open pull request for this project, but you can add to the existing pull request."_ I'll try putting the fix in a separate branch to see if it solves the issue.

**Comment by IQAndreas** [comment]
Thanks for the helping hand. 

I noticed you already fixed issue #2, so that change has not been included. The other changes are confined to their separate branches and new pull requests have been sent out, so I'm closing this one.

**Comment by mpalmer** [comment]
> I'll try putting the fix in a separate branch to see if it solves the issue.

Yes, all pull requests are branch-oriented, not commit oriented, so you can't have two pull requests for the same branch.  The UI doesn't make that distinction quite as obvious as it should be, IMO.

**Pull request closed without merging**
